# SPDX-FileCopyrightText: 2025 ash_typescript contributors <https://github.com/ash-project/ash_typescript/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshTypescript.TypedController.CodegenTest do
  use ExUnit.Case

  alias AshTypescript.Test.CodegenTestHelper

  @moduletag :ash_typescript

  # Snapshot the global config this module mutates so it cannot leak into
  # later test modules.
  setup_all do
    AshTypescript.Test.TestHelpers.restore_application_env_on_exit([
      :generate_effect_schemas,
      :generate_valibot_schemas,
      :generate_zod_schemas,
      :typed_controller_after_request_hook,
      :typed_controller_before_request_hook,
      :typed_controller_hook_context_type,
      :typed_controller_import_into_generated,
      :typed_controller_mode,
      :typed_controller_path_params_style
    ])
  end

  setup_all do
    {:ok, files} = CodegenTestHelper.generate_files()
    typescript = CodegenTestHelper.routes_content(files)
    %{typescript: typescript, files: files}
  end

  describe "multi-mount code generation" do
    setup do
      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceMultiMountRouter
        )

      %{typescript: typescript}
    end

    test "generates prefixed path helpers for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export function adminAuthPath(")
      assert String.contains?(typescript, "export function appAuthPath(")
    end

    test "generates prefixed action functions for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function adminLogin(")
      assert String.contains?(typescript, "export async function appLogin(")
    end

    test "generates prefixed input types for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export type AdminLoginInput = {")
      assert String.contains?(typescript, "export type AppLoginInput = {")
    end

    test "GET fetch functions pass path and query params through to the path helper", %{
      typescript: typescript
    } do
      # :user_id is a path param at the admin mount only
      assert String.contains?(
               typescript,
               "export async function adminProfile(path: { userId: string }, " <>
                 "query?: { bio?: string | null }, config?: TypedControllerConfig): " <>
                 "Promise<TypedControllerResponse<AdminProfileResult>> {\n" <>
                 "  return executeTypedControllerRequest(adminProfilePath(path, query), "
             )

      assert String.contains?(
               typescript,
               "executeTypedControllerRequest(appProfilePath(query), "
             )
    end

    test "generates prefixed PATCH functions for each scope", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function adminUpdateProvider(")
      assert String.contains?(typescript, "export async function appUpdateProvider(")
    end

    test "generates prefixed input types for PATCH routes", %{typescript: typescript} do
      assert String.contains?(typescript, "export type AdminUpdateProviderInput = {")
      assert String.contains?(typescript, "export type AppUpdateProviderInput = {")
    end

    test "generates prefixed path helpers for mutation routes", %{typescript: typescript} do
      assert String.contains?(typescript, "export function adminLoginPath(")
      assert String.contains?(typescript, "export function appLoginPath(")
      assert String.contains?(typescript, "export function adminLogoutPath(")
      assert String.contains?(typescript, "export function appLogoutPath(")
    end

    test "does not generate unprefixed helpers when multi-mounted", %{typescript: typescript} do
      refute Regex.match?(~r/function authPath\(/, typescript)
      refute Regex.match?(~r/function login\(/, typescript)
    end
  end

  describe "ambiguous mount error" do
    test "raises when router has duplicate mounts without as: options" do
      assert_raise RuntimeError, ~r/don't have unique `as:` options/, fn ->
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceAmbiguousRouter
        )
      end
    end
  end

  describe "GET route path helpers" do
    test "generates non-empty TypeScript output", %{typescript: typescript} do
      assert typescript != ""
      assert String.contains?(typescript, "// This file is auto-generated by AshTypescript")
    end

    test "generates path helper for auth route", %{typescript: typescript} do
      assert String.contains?(typescript, "export function authPath(")
      assert String.contains?(typescript, "return \"/auth\"")
    end

    test "generates path helper for provider_page route with path param and query param", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export function providerPagePath(")
      assert String.contains?(typescript, "path: { provider: string }")
      assert String.contains?(typescript, "query?: { tab?: string | null }")
    end

    test "GET path helper with path params uses path object in URL template", %{
      typescript: typescript
    } do
      [_, after_provider_page] =
        String.split(typescript, "export function providerPagePath(", parts: 2)

      [provider_page_body | _] = String.split(after_provider_page, "\n}\n", parts: 2)
      assert String.contains?(provider_page_body, "${encodeURIComponent(path.provider)}")
    end

    # Regression: path-param values must be encodeURIComponent-wrapped so a value
    # cannot alter URL structure. Without encoding, a "/"-prefixed value on a
    # leading-param route ("/:slug") forms a protocol-relative URL that redirects
    # the request — and its credentialed headers — to another host (CVE-3215).
    test "path helper and action wrap every path param in encodeURIComponent", %{
      typescript: typescript
    } do
      # Raw interpolation of a path param must never appear anywhere.
      refute String.contains?(typescript, "${path.provider}")
      assert String.contains?(typescript, "${encodeURIComponent(path.provider)}")

      # Both the GET path helper and the mutation action function must encode.
      for anchor <- ["export function providerPagePath(", "export async function updateProvider("] do
        [_, after_anchor] = String.split(typescript, anchor, parts: 2)
        [body | _] = String.split(after_anchor, "\n}\n", parts: 2)
        assert String.contains?(body, "${encodeURIComponent(path.provider)}")
        refute String.contains?(body, "${path.provider}")
      end
    end

    test "generates path helper for search route with required query param", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export function searchPath(")

      assert String.contains?(
               typescript,
               "query: { q: string; page?: number | null; tags?: Array<string> | null }"
             )
    end

    test "array query params append one name[] pair per element", %{typescript: typescript} do
      # String(array) would comma-join the whole list into a single value, which
      # Plug's query parser cannot rebuild into a list
      assert String.contains?(
               typescript,
               ~s|query.tags.forEach((v) => searchParams.append("tags[]", String(v)))|
             )
    end

    test "optional query params are skipped when explicitly null", %{typescript: typescript} do
      # Without the null guard, `String(null)` would send the literal "null"
      assert String.contains?(
               typescript,
               ~s|if (query?.page !== undefined && query?.page !== null)|
             )
    end

    test "generates URLSearchParams for GET routes with query params", %{typescript: typescript} do
      assert String.contains?(typescript, "new URLSearchParams()")
      assert String.contains?(typescript, "searchParams.set(")
      assert String.contains?(typescript, "searchParams.toString()")
    end

    test "GET path helpers do not generate async functions", %{typescript: typescript} do
      for path_fn <- ["authPath()", "providerPagePath(", "searchPath("] do
        assert String.contains?(typescript, "export function #{path_fn}")
        refute String.contains?(typescript, "export async function #{path_fn}")
      end
    end

    test "GET routes without returns get no fetch function", %{typescript: typescript} do
      refute String.contains?(typescript, "export async function auth(")
      refute String.contains?(typescript, "export async function providerPage(")
    end

    test "generates JSDoc for path helpers", %{typescript: typescript} do
      assert String.contains?(typescript, "Path helper for /auth")
      assert String.contains?(typescript, "Path helper for /auth/providers/:provider")
    end
  end

  describe "POST route action functions" do
    test "generates typed input type for login action", %{typescript: typescript} do
      assert String.contains?(typescript, "export type LoginInput = {")
      assert String.contains?(typescript, "code: string;")
      assert String.contains?(typescript, "rememberMe?: boolean | null;")
    end

    test "generates async function for login with input param", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function login(")
      assert String.contains?(typescript, "input: LoginInput")
      assert String.contains?(typescript, "Promise<Response>")
    end

    test "login function sends POST with JSON body via helper", %{typescript: typescript} do
      assert String.contains?(typescript, "\"POST\", \"login\", JSON.stringify(input)")
    end

    test "generates async function for logout without input param", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function logout(")
      assert String.contains?(typescript, "config?: TypedControllerConfig")
      refute String.contains?(typescript, "LogoutInput")
    end

    test "logout function sends POST without body", %{typescript: typescript} do
      [_, after_logout] = String.split(typescript, "export async function logout(", parts: 2)
      [logout_body | _] = String.split(after_logout, "\n}\n", parts: 2)
      refute String.contains?(logout_body, "body:")
    end

    test "action functions accept TypedControllerConfig", %{typescript: typescript} do
      assert String.contains?(typescript, "config?: TypedControllerConfig")
    end

    test "generates JSDoc for action functions", %{typescript: typescript} do
      assert String.contains?(typescript, "POST /auth/login")
      assert String.contains?(typescript, "POST /auth/logout")
    end

    test "generates path helper alongside login action function", %{typescript: typescript} do
      assert String.contains?(typescript, "export function loginPath(")
      assert String.contains?(typescript, "return \"/auth/login\"")
    end

    test "generates path helper alongside logout action function", %{typescript: typescript} do
      assert String.contains?(typescript, "export function logoutPath(")
      assert String.contains?(typescript, "return \"/auth/logout\"")
    end
  end

  describe "route result types" do
    test "exports a plain object result type for map returns", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               "export type LoginResult = {userId: UUID, rememberMe: boolean | null, " <>
                 "session: {expiresAt: UtcDateTime | null}};"
             )
    end

    test "maps NewType fields through typescript_field_names without selection metadata", %{
      typescript: typescript
    } do
      assert String.contains?(
               typescript,
               "export type UpdateProviderResult = {field1: string, isActive: boolean, line2: string | null};"
             )

      refute typescript =~ ~r/export type \w+Result = .*__type/
    end

    test "maps primitive returns directly", %{typescript: typescript} do
      assert String.contains?(typescript, "export type CreateTaskResult = number;")
    end

    test "maps a map without fields constraints to the untyped map type", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export type ProfileResult = Record<string, any>;")
    end

    test "expands NewTypes not reachable from RPC, with inline enums and untyped nested maps",
         %{typescript: typescript} do
      assert String.contains?(
               typescript,
               "export type RegisterResult = {totalCount: number, " <>
                 ~s[status: "ok" | "pending", extra: Record<string, any> | null};]
             )
    end

    test "exports result types for GET routes", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               "export type SearchResult = Array<{id: UUID, title: string | null, tagNames: Array<string>}>;"
             )
    end

    test "action functions of routes declaring returns resolve to a typed response", %{
      typescript: typescript
    } do
      assert String.contains?(
               typescript,
               "export async function login(input: LoginInput, config?: TypedControllerConfig): " <>
                 "Promise<TypedControllerResponse<LoginResult>> {"
             )

      assert String.contains?(
               typescript,
               "Promise<TypedControllerResponse<UpdateProviderResult>>"
             )
    end

    test "action functions of routes declaring returns request JSON", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               ~s[return executeTypedControllerRequest("/auth/login", "POST", "login", ] <>
                 ~s[JSON.stringify(input), config, { Accept: "application/json" });]
             )
    end

    test "GET routes declaring returns get a fetch function built on the path helper", %{
      typescript: typescript
    } do
      assert String.contains?(
               typescript,
               "export async function search(query: { q: string; page?: number | null; " <>
                 "tags?: Array<string> | null }, config?: TypedControllerConfig): " <>
                 "Promise<TypedControllerResponse<SearchResult>> {\n" <>
                 ~s[  return executeTypedControllerRequest(searchPath(query), "GET", "search", ] <>
                 ~s[undefined, config, { Accept: "application/json" });]
             )

      # All-optional query args keep the query parameter optional
      assert String.contains?(
               typescript,
               "export async function profile(query?: { userId?: string | null; " <>
                 "bio?: string | null }, config?: TypedControllerConfig): " <>
                 "Promise<TypedControllerResponse<ProfileResult>> {"
             )

      assert String.contains?(typescript, " * GET /search\n")
    end

    test "routes without returns send no Accept header", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               ~s[return executeTypedControllerRequest("/auth/logout", "POST", "logout", undefined, config);]
             )
    end

    test "helper sends Content-Type only with a body and merges default headers before config headers",
         %{typescript: typescript} do
      assert String.contains?(typescript, "defaultHeaders?: Record<string, string>,")

      assert typescript =~
               ~r/\.\.\.\(body !== undefined \? \{ "Content-Type": "application\/json" \} : \{\}\),\s+\.\.\.defaultHeaders,\s+\.\.\.processedConfig\.headers,/
    end

    test "routes without returns keep resolving to a plain Response", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               "export async function logout(config?: TypedControllerConfig): Promise<Response> {"
             )

      refute String.contains?(typescript, "LogoutResult")
    end

    test "generates the TypedControllerResponse type discriminated on ok", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export type TypedControllerResponse<T> =")

      assert String.contains?(
               typescript,
               ~s[(Omit<Response, "ok" | "json"> & { ok: true; json(): Promise<T> })]
             )

      assert String.contains?(
               typescript,
               ~s[(Omit<Response, "ok" | "json"> & { ok: false; json(): Promise<unknown> })]
             )
    end

    test "imports shared types referenced only by result types", %{typescript: typescript} do
      assert typescript =~ ~r/import type \{[^}]*\bUtcDateTime\b[^}]*\} from/
    end
  end

  describe "path param validation" do
    test "raises when path param has no matching DSL argument" do
      route_info = %{
        source_module: AshTypescript.Test.Session,
        controller: AshTypescript.Test.SessionController,
        route: %{
          name: :broken,
          method: :get,
          arguments: [],
          run: fn conn, _params -> conn end,
          description: nil,
          deprecated: nil
        },
        path: "/items/:id",
        method: :get,
        path_params: [:id],
        scope_prefix: nil
      }

      assert_raise RuntimeError, ~r/don't have matching DSL arguments/, fn ->
        AshTypescript.TypedController.Codegen.validate_path_param_arguments!([route_info])
      end
    end
  end

  describe "path param allow_nil? validation" do
    defp make_route_info(opts) do
      route_name = Keyword.fetch!(opts, :name)
      arguments = Keyword.get(opts, :arguments, [])
      path_params = Keyword.get(opts, :path_params, [])
      path = Keyword.get(opts, :path, "/test")
      source_module = Keyword.get(opts, :source_module, AshTypescript.Test.Session)

      args =
        Enum.map(arguments, fn {name, type, arg_opts} ->
          %AshTypescript.TypedController.Dsl.RouteArgument{
            name: name,
            type: type,
            allow_nil?: Keyword.get(arg_opts, :allow_nil?, true)
          }
        end)

      %{
        source_module: source_module,
        controller: AshTypescript.Test.SessionController,
        route: %{
          name: route_name,
          method: :get,
          arguments: args,
          run: fn conn, _params -> conn end,
          description: nil,
          deprecated: nil
        },
        path: path,
        method: :get,
        path_params: path_params,
        scope_prefix: nil
      }
    end

    test "raises when single-mount path param has allow_nil?: true" do
      route_info =
        make_route_info(
          name: :show,
          arguments: [{:id, :string, []}],
          path: "/items/:id",
          path_params: [:id]
        )

      assert_raise RuntimeError, ~r/allow_nil\?: true.*can never be nil/s, fn ->
        AshTypescript.TypedController.Codegen.validate_path_param_arguments!([route_info])
      end
    end

    test "raises when multi-mount path param is present at ALL mounts with allow_nil?: true" do
      base_opts = [
        name: :show,
        arguments: [{:id, :string, []}],
        path_params: [:id]
      ]

      mount1 = make_route_info([path: "/admin/items/:id", source_module: MyApp.Item] ++ base_opts)
      mount2 = make_route_info([path: "/app/items/:id", source_module: MyApp.Item] ++ base_opts)

      assert_raise RuntimeError, ~r/allow_nil\?: true.*can never be nil/s, fn ->
        AshTypescript.TypedController.Codegen.validate_path_param_arguments!([mount1, mount2])
      end
    end

    test "does not raise when multi-mount path param is only at SOME mounts with allow_nil?: true" do
      args = [{:id, :string, []}]

      mount_with_param =
        make_route_info(
          name: :show,
          arguments: args,
          path: "/items/:id",
          path_params: [:id],
          source_module: MyApp.Item
        )

      mount_without_param =
        make_route_info(
          name: :show,
          arguments: args,
          path: "/items",
          path_params: [],
          source_module: MyApp.Item
        )

      AshTypescript.TypedController.Codegen.validate_path_param_arguments!([
        mount_with_param,
        mount_without_param
      ])
    end

    test "does not raise when path param has allow_nil?: false" do
      route_info =
        make_route_info(
          name: :show,
          arguments: [{:id, :string, [allow_nil?: false]}],
          path: "/items/:id",
          path_params: [:id]
        )

      AshTypescript.TypedController.Codegen.validate_path_param_arguments!([route_info])
    end

    test "error message suggests setting allow_nil?: false" do
      route_info =
        make_route_info(
          name: :show,
          arguments: [{:id, :string, []}],
          path: "/items/:id",
          path_params: [:id]
        )

      assert_raise RuntimeError, ~r/allow_nil\?: false/, fn ->
        AshTypescript.TypedController.Codegen.validate_path_param_arguments!([route_info])
      end
    end

    test "raises when multi-mount path param at SOME mounts has allow_nil?: false" do
      args = [{:id, :string, [allow_nil?: false]}]

      mount_with_param =
        make_route_info(
          name: :show,
          arguments: args,
          path: "/items/:id",
          path_params: [:id],
          source_module: MyApp.Item
        )

      mount_without_param =
        make_route_info(
          name: :show,
          arguments: args,
          path: "/items",
          path_params: [],
          source_module: MyApp.Item
        )

      assert_raise RuntimeError, ~r/allow_nil\?: false.*will be nil at others/s, fn ->
        AshTypescript.TypedController.Codegen.validate_path_param_arguments!([
          mount_with_param,
          mount_without_param
        ])
      end
    end
  end

  describe "path param allow_nil? integration — always present error" do
    test "raises when :tab is always a path param but has allow_nil?: true" do
      assert_raise RuntimeError, ~r/allow_nil\?: true.*can never be nil/s, fn ->
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.AllowNilAlwaysPresentErrorRouter
        )
      end
    end
  end

  describe "path param allow_nil? integration — sometimes present error" do
    test "raises when :provider is a path param at some mounts but has allow_nil?: false" do
      assert_raise RuntimeError, ~r/allow_nil\?: false.*will be nil at others/s, fn ->
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.AllowNilSometimesPresentErrorRouter
        )
      end
    end
  end

  describe "path param allow_nil? integration — asymmetric multi-mount happy path" do
    setup do
      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceMultiMountRouter
        )

      %{typescript: typescript}
    end

    test "generates admin profile path with user_id as path param", %{typescript: typescript} do
      assert String.contains?(typescript, "export function adminProfilePath(")
      assert String.contains?(typescript, "path: { userId: string }")
    end

    test "admin profile path uses path param in URL template", %{typescript: typescript} do
      [_, after_admin_profile] =
        String.split(typescript, "export function adminProfilePath(", parts: 2)

      [admin_profile_body | _] = String.split(after_admin_profile, "\n}\n", parts: 2)
      assert String.contains?(admin_profile_body, "${encodeURIComponent(path.userId)}")
    end

    test "generates app profile path with user_id as query param", %{typescript: typescript} do
      assert String.contains?(typescript, "export function appProfilePath(")

      [_, after_app_profile] =
        String.split(typescript, "export function appProfilePath(", parts: 2)

      [app_profile_body | _] = String.split(after_app_profile, "\n}\n", parts: 2)
      refute String.contains?(app_profile_body, "${path.userId}")
      assert String.contains?(app_profile_body, "query")
    end

    test "admin and app profile paths point to different URLs", %{typescript: typescript} do
      assert String.contains?(typescript, "Path helper for /admin/profile/:user_id")
      assert String.contains?(typescript, "Path helper for /app/profile")
    end
  end

  describe "PATCH route with path params and input" do
    test "generates typed input type for update_provider action excluding path params", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export type UpdateProviderInput = {")
      assert String.contains?(typescript, "enabled: boolean;")
      assert String.contains?(typescript, "displayName?: string | null;")
      refute String.contains?(typescript, "UpdateProviderInput = {\n  provider")
    end

    test "generates async function with path and input params", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function updateProvider(")
      assert String.contains?(typescript, "path: { provider: string }")
      assert String.contains?(typescript, "input: UpdateProviderInput")
      assert String.contains?(typescript, "Promise<Response>")
    end

    test "update_provider function sends PATCH with JSON body via helper", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "\"PATCH\", \"updateProvider\", JSON.stringify(input)")
    end

    test "update_provider function uses path object for URL template", %{typescript: typescript} do
      assert String.contains?(typescript, "${encodeURIComponent(path.provider)}")
    end

    test "generates JSDoc for PATCH action", %{typescript: typescript} do
      assert String.contains?(typescript, "PATCH /auth/providers/:provider")
    end

    test "generates path helper alongside PATCH action function", %{typescript: typescript} do
      assert String.contains?(typescript, "export function updateProviderPath(")
      assert String.contains?(typescript, "path: { provider: string }")
      assert String.contains?(typescript, "Path helper for /auth/providers/:provider")
    end
  end

  describe "typed_controller_path_params_style: :args" do
    setup do
      previous = Application.get_env(:ash_typescript, :typed_controller_path_params_style)
      Application.put_env(:ash_typescript, :typed_controller_path_params_style, :args)

      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn ->
        if previous do
          Application.put_env(:ash_typescript, :typed_controller_path_params_style, previous)
        else
          Application.delete_env(:ash_typescript, :typed_controller_path_params_style)
        end
      end)

      %{typescript: typescript}
    end

    test "GET fetch functions pass positional path params through to the path helper" do
      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceMultiMountRouter
        )

      assert String.contains?(
               typescript,
               "export async function adminProfile(userId: string, " <>
                 "query?: { bio?: string | null }, config?: TypedControllerConfig): " <>
                 "Promise<TypedControllerResponse<AdminProfileResult>> {\n" <>
                 "  return executeTypedControllerRequest(adminProfilePath(userId, query), "
             )
    end

    test "GET path helper uses flat positional args for path params", %{typescript: typescript} do
      assert String.contains?(typescript, "export function providerPagePath(provider: string,")
      refute String.contains?(typescript, "providerPagePath(path:")
    end

    test "GET path helper URL template accesses params directly", %{typescript: typescript} do
      [_, after_provider_page] =
        String.split(typescript, "export function providerPagePath(", parts: 2)

      [provider_page_body | _] = String.split(after_provider_page, "\n}\n", parts: 2)
      assert String.contains?(provider_page_body, "${encodeURIComponent(provider)}")
      refute String.contains?(provider_page_body, "${path.provider}")
    end

    test "mutation action function uses flat positional args for path params", %{
      typescript: typescript
    } do
      assert String.contains?(
               typescript,
               "export async function updateProvider(provider: string,"
             )

      refute String.contains?(typescript, "updateProvider(path:")
    end

    test "mutation action function URL template accesses params directly", %{
      typescript: typescript
    } do
      [_, after_update_provider] =
        String.split(typescript, "export async function updateProvider(", parts: 2)

      [update_provider_body | _] = String.split(after_update_provider, "\n}\n", parts: 2)
      assert String.contains?(update_provider_body, "${encodeURIComponent(provider)}")
      refute String.contains?(update_provider_body, "${path.provider}")
    end

    test "mutation path helper uses flat positional args", %{typescript: typescript} do
      assert String.contains?(typescript, "export function updateProviderPath(provider: string)")
      refute String.contains?(typescript, "updateProviderPath(path:")
    end
  end

  describe "typed_controller_mode: :paths_only" do
    setup do
      previous = Application.get_env(:ash_typescript, :typed_controller_mode)
      Application.put_env(:ash_typescript, :typed_controller_mode, :paths_only)

      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn ->
        if previous do
          Application.put_env(:ash_typescript, :typed_controller_mode, previous)
        else
          Application.delete_env(:ash_typescript, :typed_controller_mode)
        end
      end)

      %{typescript: typescript}
    end

    test "generates path helpers for all routes", %{typescript: typescript} do
      assert String.contains?(typescript, "export function authPath(")
      assert String.contains?(typescript, "export function providerPagePath(")
      assert String.contains?(typescript, "export function searchPath(")
      assert String.contains?(typescript, "export function loginPath(")
      assert String.contains?(typescript, "export function logoutPath(")
      assert String.contains?(typescript, "export function updateProviderPath(")
      assert String.contains?(typescript, "export function echoParamsPath(")
    end

    test "does not generate async action functions", %{typescript: typescript} do
      refute String.contains?(typescript, "async function")
      refute String.contains?(typescript, "executeTypedControllerRequest(")
      refute String.contains?(typescript, "Promise<Response>")
    end

    test "does not generate input types", %{typescript: typescript} do
      refute String.contains?(typescript, "export type LoginInput")
      refute String.contains?(typescript, "export type UpdateProviderInput")
      refute String.contains?(typescript, "export type EchoParamsInput")
    end

    test "still generates query params for GET routes", %{typescript: typescript} do
      assert String.contains?(typescript, "query?: { tab?: string | null }")

      assert String.contains?(
               typescript,
               "query: { q: string; page?: number | null; tags?: Array<string> | null }"
             )
    end

    test "does not generate TypedControllerConfig or helper", %{typescript: typescript} do
      refute String.contains?(typescript, "TypedControllerConfig")
      refute String.contains?(typescript, "executeTypedControllerRequest")
      refute String.contains?(typescript, "TypedControllerResponse")
    end

    test "does not generate fetch functions for GET routes declaring returns", %{
      typescript: typescript
    } do
      refute String.contains?(typescript, "export async function search(")
    end

    test "still exports result types", %{typescript: typescript} do
      assert String.contains?(typescript, "export type LoginResult = {")
      assert String.contains?(typescript, "export type SearchResult = Array<")
    end
  end

  describe "TypedControllerConfig interface and helper" do
    test "generates TypedControllerConfig interface", %{typescript: typescript} do
      assert String.contains?(typescript, "export interface TypedControllerConfig {")
      assert String.contains?(typescript, "headers?: Record<string, string>")
      assert String.contains?(typescript, "fetchOptions?: RequestInit")
      assert String.contains?(typescript, "customFetch?: (")
    end

    test "generates executeTypedControllerRequest helper", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function executeTypedControllerRequest(")
      assert String.contains?(typescript, "url: string")
      assert String.contains?(typescript, "method: string")
      assert String.contains?(typescript, "actionName: string")
      assert String.contains?(typescript, "body: string | undefined")
      assert String.contains?(typescript, "config?: TypedControllerConfig")
    end

    test "mutation functions call executeTypedControllerRequest", %{typescript: typescript} do
      assert String.contains?(typescript, "return executeTypedControllerRequest(")
    end

    test "no hookCtx field when hooks not configured" do
      prev_before = Application.get_env(:ash_typescript, :typed_controller_before_request_hook)
      prev_after = Application.get_env(:ash_typescript, :typed_controller_after_request_hook)
      prev_ctx = Application.get_env(:ash_typescript, :typed_controller_hook_context_type)

      Application.delete_env(:ash_typescript, :typed_controller_before_request_hook)
      Application.delete_env(:ash_typescript, :typed_controller_after_request_hook)
      Application.delete_env(:ash_typescript, :typed_controller_hook_context_type)

      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      reset_env(:typed_controller_before_request_hook, prev_before)
      reset_env(:typed_controller_after_request_hook, prev_after)
      reset_env(:typed_controller_hook_context_type, prev_ctx)

      refute String.contains?(typescript, "hookCtx?:")
      refute String.contains?(typescript, "TypedControllerHookContext")
    end
  end

  describe "typed controller hooks" do
    setup do
      prev_before = Application.get_env(:ash_typescript, :typed_controller_before_request_hook)
      prev_after = Application.get_env(:ash_typescript, :typed_controller_after_request_hook)
      prev_ctx = Application.get_env(:ash_typescript, :typed_controller_hook_context_type)

      Application.put_env(
        :ash_typescript,
        :typed_controller_before_request_hook,
        "RouteHooks.beforeRequest"
      )

      Application.put_env(
        :ash_typescript,
        :typed_controller_after_request_hook,
        "RouteHooks.afterRequest"
      )

      Application.put_env(
        :ash_typescript,
        :typed_controller_hook_context_type,
        "MyRouteHookContext"
      )

      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn ->
        reset_env(:typed_controller_before_request_hook, prev_before)
        reset_env(:typed_controller_after_request_hook, prev_after)
        reset_env(:typed_controller_hook_context_type, prev_ctx)
      end)

      %{typescript: typescript}
    end

    test "generates hook context type", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               "export type TypedControllerHookContext = MyRouteHookContext;"
             )
    end

    test "generates hookCtx field in config interface", %{typescript: typescript} do
      assert String.contains?(typescript, "hookCtx?: TypedControllerHookContext;")
    end

    test "before hook call appears in helper", %{typescript: typescript} do
      assert String.contains?(typescript, "RouteHooks.beforeRequest")
      assert String.contains?(typescript, "processedConfig = await RouteHooks.beforeRequest(")
    end

    test "after hook call appears in helper", %{typescript: typescript} do
      assert String.contains?(typescript, "RouteHooks.afterRequest")
      assert String.contains?(typescript, "await RouteHooks.afterRequest(")
    end
  end

  describe "typed controller custom imports" do
    setup do
      prev = Application.get_env(:ash_typescript, :typed_controller_import_into_generated)

      Application.put_env(
        :ash_typescript,
        :typed_controller_import_into_generated,
        [%{import_name: "RouteHooks", file: "./test/ts/routeHooks.ts"}]
      )

      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn ->
        reset_env(:typed_controller_import_into_generated, prev)
      end)

      %{typescript: typescript}
    end

    test "custom imports appear in generated output", %{typescript: typescript} do
      assert String.contains?(
               typescript,
               "import * as RouteHooks from \"./routeHooks\";"
             )
    end
  end

  describe "Zod schema generation" do
    setup %{files: files} do
      zod = CodegenTestHelper.zod_content(files)
      %{zod: zod}
    end

    test "generates Zod schemas for mutation routes with input args", %{zod: zod} do
      assert String.contains?(zod, "export const loginZodSchema = z.object({")
      # Implicit min(1) from the folded allow_empty?: false string default —
      # the request handler applies string constraints, so "" is rejected
      # server-side for this required argument and the schema mirrors that
      assert String.contains?(zod, "code: z.string().min(1),")
      assert String.contains?(zod, "rememberMe: z.boolean().nullable().optional(),")
    end

    test "generates Zod schema for update_provider excluding path params", %{zod: zod} do
      assert String.contains?(zod, "export const updateProviderZodSchema = z.object({")
      assert String.contains?(zod, "enabled: z.boolean(),")
      assert String.contains?(zod, "displayName: z.string().min(1).nullable().optional(),")

      [_, after_schema] =
        String.split(zod, "export const updateProviderZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)
      refute String.contains?(schema_body, "provider")
    end

    test "generates Zod import in zod file", %{zod: zod} do
      assert String.contains?(zod, "import { z } from \"zod\";")
    end

    test "no Zod schema for mutation routes without input args", %{zod: zod} do
      refute String.contains?(zod, "logoutZodSchema")
    end

    test "maps types correctly - string, boolean, integer", %{zod: zod} do
      assert String.contains?(zod, "export const echoParamsZodSchema = z.object({")

      [_, after_schema] =
        String.split(zod, "export const echoParamsZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)
      assert String.contains?(schema_body, "name: z.string().min(1),")
      assert String.contains?(schema_body, "count: z.number().int().nullable().optional(),")
      assert String.contains?(schema_body, "active: z.boolean().nullable().optional(),")
    end
  end

  describe "Zod schema generation with type constraints" do
    setup %{files: files} do
      zod = CodegenTestHelper.zod_content(files)
      %{zod: zod}
    end

    test "generates string constraints: min_length, max_length, regex", %{zod: zod} do
      assert String.contains?(zod, "export const registerZodSchema = z.object({")

      [_, after_schema] =
        String.split(zod, "export const registerZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(
               schema_body,
               "username: z.string().min(3).max(20).regex(/^[a-zA-Z0-9_]+$/),"
             )

      assert String.contains?(
               schema_body,
               "email: z.string().min(1).regex(/^[^@]+@[^@]+\\.[^@]+$/),"
             )
    end

    test "generates integer constraints: min, max", %{zod: zod} do
      [_, after_schema] =
        String.split(zod, "export const registerZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(schema_body, "age: z.number().int().min(13).max(120),")
    end

    test "generates float constraints: min, max", %{zod: zod} do
      [_, after_schema] =
        String.split(zod, "export const registerZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(
               schema_body,
               "score: z.number().min(0.0).max(100.0).nullable().optional(),"
             )
    end

    test "generates string max_length-only constraint", %{zod: zod} do
      [_, after_schema] =
        String.split(zod, "export const registerZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(
               schema_body,
               "bio: z.string().min(1).max(500).nullable().optional(),"
             )
    end

    test "generates fixed-length string via min_length + max_length", %{zod: zod} do
      [_, after_schema] =
        String.split(zod, "export const registerZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(
               schema_body,
               "inviteCode: z.string().min(8).max(8).nullable().optional(),"
             )
    end

    test "generates corresponding TypeScript input type in routes file", %{typescript: typescript} do
      assert String.contains?(typescript, "export type RegisterInput = {")
      assert String.contains?(typescript, "username: string;")
      assert String.contains?(typescript, "email: string;")
      assert String.contains?(typescript, "age: number;")
      assert String.contains?(typescript, "score?: number | null;")
      assert String.contains?(typescript, "bio?: string | null;")
      assert String.contains?(typescript, "inviteCode?: string | null;")
    end
  end

  describe "embedded resource argument type" do
    setup %{files: files} do
      types = CodegenTestHelper.types_content(files)
      zod = CodegenTestHelper.zod_content(files)
      %{types: types, zod: zod}
    end

    test "generates input type with embedded resource reference in routes file", %{
      typescript: typescript
    } do
      assert String.contains?(typescript, "export type CreateTaskInput = {")
      assert String.contains?(typescript, "title: string;")
      assert String.contains?(typescript, "metadata: TaskMetadataInputSchema;")
      assert String.contains?(typescript, "priority?: number | null;")
    end

    test "generates Zod schema referencing embedded resource Zod schema", %{zod: zod} do
      assert String.contains?(zod, "export const createTaskRouteZodSchema = z.object({")

      [_, after_schema] =
        String.split(zod, "export const createTaskRouteZodSchema = z.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(schema_body, "title: z.string().min(1).max(200),")
      assert String.contains?(schema_body, "metadata: TaskMetadataZodSchema,")

      assert String.contains?(
               schema_body,
               "priority: z.number().int().min(1).max(5).nullable().optional(),"
             )
    end

    test "generates action function for create_task in routes file", %{typescript: typescript} do
      assert String.contains?(typescript, "export async function createTask(")
      assert String.contains?(typescript, "input: CreateTaskInput")
    end

    test "generates TaskMetadataInputSchema type definition in types file", %{types: types} do
      assert String.contains?(types, "export type TaskMetadataInputSchema = {")
      assert String.contains?(types, "createdBy: string;")
    end

    test "generates TaskMetadataZodSchema in zod file", %{zod: zod} do
      assert String.contains?(zod, "export const TaskMetadataZodSchema = z.object({")
    end

    test "types file defines TaskMetadataInputSchema referenced by routes file", %{
      types: types,
      typescript: typescript
    } do
      assert String.contains?(types, "export type TaskMetadataInputSchema")
      assert String.contains?(typescript, "metadata: TaskMetadataInputSchema;")
    end
  end

  describe "Zod schema generation disabled" do
    setup do
      prev = Application.get_env(:ash_typescript, :generate_zod_schemas)
      Application.put_env(:ash_typescript, :generate_zod_schemas, false)

      typescript =
        CodegenTestHelper.generate_controller_content(
          router: AshTypescript.Test.ControllerResourceTestRouter
        )

      on_exit(fn -> reset_env(:generate_zod_schemas, prev) end)
      %{typescript: typescript}
    end

    test "no Zod schemas in output", %{typescript: typescript} do
      refute String.contains?(typescript, "z.object")
      refute String.contains?(typescript, "ZodSchema")
    end

    test "no Zod import", %{typescript: typescript} do
      refute String.contains?(typescript, "import { z }")
    end
  end

  describe "Valibot schema generation" do
    setup %{files: files} do
      valibot = CodegenTestHelper.valibot_content(files)
      %{valibot: valibot}
    end

    test "generates Valibot schemas for mutation routes with input args", %{valibot: valibot} do
      assert String.contains?(valibot, "export const loginValibotSchema = v.object({")
      # Implicit minLength(1) from the folded allow_empty?: false string default —
      # the request handler applies string constraints, so "" is rejected
      # server-side for this required argument and the schema mirrors that
      assert String.contains?(valibot, "code: v.pipe(v.string(), v.minLength(1)),")
      assert String.contains?(valibot, "rememberMe: v.optional(v.nullable(v.boolean())),")
    end

    test "generates Valibot schema for update_provider excluding path params", %{
      valibot: valibot
    } do
      assert String.contains?(valibot, "export const updateProviderValibotSchema = v.object({")
      assert String.contains?(valibot, "enabled: v.boolean(),")

      assert String.contains?(
               valibot,
               "displayName: v.optional(v.nullable(v.pipe(v.string(), v.minLength(1)))),"
             )

      [_, after_schema] =
        String.split(valibot, "export const updateProviderValibotSchema = v.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)
      refute String.contains?(schema_body, "provider")
    end

    test "generates Valibot import in valibot file", %{valibot: valibot} do
      assert String.contains?(valibot, "import * as v from \"valibot\";")
    end

    test "no Valibot schema for mutation routes without input args", %{valibot: valibot} do
      refute String.contains?(valibot, "logoutValibotSchema")
    end

    test "maps types correctly - string, boolean, integer", %{valibot: valibot} do
      assert String.contains?(valibot, "export const echoParamsValibotSchema = v.object({")

      [_, after_schema] =
        String.split(valibot, "export const echoParamsValibotSchema = v.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)
      assert String.contains?(schema_body, "name: v.pipe(v.string(), v.minLength(1)),")

      assert String.contains?(
               schema_body,
               "count: v.optional(v.nullable(v.pipe(v.number(), v.integer()))),"
             )

      assert String.contains?(schema_body, "active: v.optional(v.nullable(v.boolean())),")
    end

    test "generates string, integer, and float constraints", %{valibot: valibot} do
      assert String.contains?(valibot, "export const registerValibotSchema = v.object({")

      [_, after_schema] =
        String.split(valibot, "export const registerValibotSchema = v.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(
               schema_body,
               "username: v.pipe(v.string(), v.minLength(3), v.maxLength(20), v.regex(/^[a-zA-Z0-9_]+$/)),"
             )

      assert String.contains?(
               schema_body,
               "email: v.pipe(v.string(), v.minLength(1), v.regex(/^[^@]+@[^@]+\\.[^@]+$/)),"
             )

      assert String.contains?(
               schema_body,
               "age: v.pipe(v.number(), v.integer(), v.minValue(13), v.maxValue(120)),"
             )

      assert String.contains?(
               schema_body,
               "score: v.optional(v.nullable(v.pipe(v.number(), v.minValue(0.0), v.maxValue(100.0)))),"
             )
    end

    test "generates Valibot schema referencing embedded resource Valibot schema", %{
      valibot: valibot
    } do
      assert String.contains?(valibot, "export const createTaskRouteValibotSchema = v.object({")

      [_, after_schema] =
        String.split(valibot, "export const createTaskRouteValibotSchema = v.object({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)

      assert String.contains?(
               schema_body,
               "title: v.pipe(v.string(), v.minLength(1), v.maxLength(200)),"
             )

      assert String.contains?(schema_body, "metadata: TaskMetadataValibotSchema,")
    end
  end

  describe "Valibot schema generation disabled" do
    setup do
      prev = Application.get_env(:ash_typescript, :generate_valibot_schemas)
      Application.put_env(:ash_typescript, :generate_valibot_schemas, false)

      on_exit(fn -> reset_env(:generate_valibot_schemas, prev) end)
      :ok
    end

    test "collects no route Valibot schemas" do
      assert AshTypescript.TypedController.Codegen.collect_route_valibot_schemas(
               router: AshTypescript.Test.ControllerResourceTestRouter
             ) == []
    end
  end

  describe "Effect schema generation" do
    setup %{files: files} do
      %{effect: CodegenTestHelper.effect_content(files)}
    end

    defp effect_schema_body(effect, name) do
      [_, after_schema] =
        String.split(effect, "export const #{name} = Schema.Struct({", parts: 2)

      [schema_body | _] = String.split(after_schema, "});", parts: 2)
      schema_body
    end

    test "imports Schema from effect", %{effect: effect} do
      assert String.contains?(effect, "import { Schema } from \"effect\";")
    end

    test "generates Effect schemas for mutation routes with input args", %{effect: effect} do
      body = effect_schema_body(effect, "loginEffectSchema")

      assert String.contains?(body, "code: Schema.String.check(Schema.isMinLength(1)),")
      assert String.contains?(body, "rememberMe: Schema.optional(Schema.NullOr(Schema.Boolean)),")
    end

    test "excludes path params from the update_provider schema", %{effect: effect} do
      body = effect_schema_body(effect, "updateProviderEffectSchema")

      assert String.contains?(body, "enabled: Schema.Boolean,")
      refute String.contains?(body, "provider")
    end

    test "no Effect schema for mutation routes without input args", %{effect: effect} do
      refute String.contains?(effect, "logoutEffectSchema")
    end

    test "generates string, integer, and float constraints", %{effect: effect} do
      body = effect_schema_body(effect, "registerEffectSchema")

      assert String.contains?(
               body,
               "username: Schema.String.check(Schema.isMinLength(3), Schema.isMaxLength(20), Schema.isPattern(/^[a-zA-Z0-9_]+$/)),"
             )

      assert String.contains?(
               body,
               "age: Schema.Int.check(Schema.isGreaterThanOrEqualTo(13), Schema.isLessThanOrEqualTo(120)),"
             )

      assert String.contains?(
               body,
               "score: Schema.optional(Schema.NullOr(Schema.Finite.check(Schema.isGreaterThanOrEqualTo(0.0), Schema.isLessThanOrEqualTo(100.0)))),"
             )
    end

    test "honors effect_schema_name and references the embedded resource schema", %{
      effect: effect
    } do
      body = effect_schema_body(effect, "createTaskRouteEffectSchema")

      assert String.contains?(body, "metadata: TaskMetadataEffectSchema,")
    end
  end

  describe "Effect schema generation disabled" do
    setup do
      prev = Application.get_env(:ash_typescript, :generate_effect_schemas)
      Application.put_env(:ash_typescript, :generate_effect_schemas, false)

      on_exit(fn -> reset_env(:generate_effect_schemas, prev) end)
      :ok
    end

    test "collects no route Effect schemas" do
      assert AshTypescript.TypedController.Codegen.collect_route_effect_schemas(
               router: AshTypescript.Test.ControllerResourceTestRouter
             ) == []
    end
  end

  describe "JSDoc @see tags" do
    test "generates @see tags on login path helper", %{typescript: typescript} do
      [_, after_login_path] =
        String.split(typescript, "/**\n * Path helper for /auth/login", parts: 2)

      [login_jsdoc | _] = String.split(after_login_path, "export function loginPath", parts: 2)
      assert String.contains?(login_jsdoc, "@see auth")
      assert String.contains?(login_jsdoc, "@see logout")
    end

    test "generates @see tags on login action function", %{typescript: typescript} do
      [_, after_login_action] =
        String.split(typescript, "/**\n * POST /auth/login", parts: 2)

      [login_action_jsdoc | _] =
        String.split(after_login_action, "export async function login", parts: 2)

      assert String.contains?(login_action_jsdoc, "@see auth")
      assert String.contains?(login_action_jsdoc, "@see logout")
    end

    test "routes without see do not have @see tags", %{typescript: typescript} do
      [_, after_auth_jsdoc] =
        String.split(typescript, "/**\n * Path helper for /auth\n", parts: 2)

      [auth_jsdoc | _] = String.split(after_auth_jsdoc, "export function authPath", parts: 2)
      refute String.contains?(auth_jsdoc, "@see")
    end
  end

  defp reset_env(key, nil), do: Application.delete_env(:ash_typescript, key)
  defp reset_env(key, value), do: Application.put_env(:ash_typescript, key, value)
end
